// The custom properties every component's CSS reads. Generated by
// `npm run tokens:css` (SPEC 0007); the stories restate none of its values.
import "@stylos/ui/tokens.css";
// The faces behind the families tokens.css names — the package supplies them.
import "@stylos/ui/fonts.css";
