#!/usr/bin/env node
// Builds the independent CSS export of @stylos/ui — SPEC 0010 §2.2.
//
//   packages/ui/src/components/<name>/<name>.css → packages/ui/dist/css/<name>.css
//   all of them, in registry order               → packages/ui/dist/css/stylos.css
//
//   npm run ui:generate    (with tokens:css, the types and the stories)
//
// A copy, in the same sense tokens:css is a projection: no transform, no
// minification, no autoprefixing — a build that improved a value on the way
// through would be a second source of it. Neither output contains tokens.css:
// a consumer links tokens separately, because that is the file a client theme
// overrides, and bundling them would make the override a cascade fight.
//
// Only built components are exported — the same rule as the other two
// generators, through the same `builtComponents`. A component directory
// without its authored CSS fails the build rather than shipping an aggregate
// quietly one component short.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { loadRegistry, slugPath } from "./lib/registry.mjs";
import { builtComponents, COMPONENTS_DIR } from "./build-ui-types.mjs";

export const OUT_DIR = "packages/ui/dist/css";
export const AGGREGATE = "stylos.css";

/**
 * The aggregate stylesheet: a generated header naming the version and the
 * components inside, then each component's CSS verbatim, in the order given.
 */
export function renderAggregate(version, parts) {
  const names = parts.map((part) => part.id).join(", ");
  const header =
    `/* GENERATED by tools/build-ui-css.mjs — do not edit.\n` +
    ` * @stylos/ui ${version} — ${parts.length} component${parts.length === 1 ? "" : "s"}: ${names}.\n` +
    ` * tokens.css is not included: link it separately — it is the file a theme overrides.\n` +
    ` */\n`;
  return [header, ...parts.map((part) => `/* ${part.id} */\n${part.css}`)].join("\n");
}

/**
 * Copies each built component's CSS and writes the aggregate. Returns the
 * written paths, relative to the root, the aggregate last.
 */
export function buildUiCss(root) {
  const entries = loadRegistry(root);
  const built = builtComponents(root, entries);

  // Registry order — the order loadRegistry states — not the order the
  // filesystem happened to return the component directories in.
  const rank = new Map(entries.map((entry, index) => [entry.id, index]));
  built.sort((a, b) => rank.get(a.id) - rank.get(b.id));

  const outDir = path.join(root, OUT_DIR);
  mkdirSync(outDir, { recursive: true });

  const written = [];
  const parts = built.map((entry) => {
    const slug = slugPath(entry.id);
    const source = path.join(root, COMPONENTS_DIR, slug, `${slug}.css`);
    if (!existsSync(source)) {
      throw new Error(
        `${COMPONENTS_DIR}/${slug}/${slug}.css is missing — ` +
          `a built component authors its CSS (SPEC 0009 §2)`
      );
    }
    const css = readFileSync(source, "utf8");
    writeFileSync(path.join(outDir, `${slug}.css`), css);
    written.push(`${OUT_DIR}/${slug}.css`);
    return { id: entry.id, css };
  });

  const { version } = JSON.parse(
    readFileSync(path.join(root, "packages/ui/package.json"), "utf8")
  );
  writeFileSync(path.join(outDir, AGGREGATE), renderAggregate(version, parts));
  written.push(`${OUT_DIR}/${AGGREGATE}`);
  return written;
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMain) {
  const root = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
  const written = buildUiCss(root);
  console.log(`OK: ${written.length} files — ${written.join(", ")}`);
}
