import test from "node:test";
import assert from "node:assert/strict";

import { defaultArgs, renderStories, storyArgTypes } from "./build-ui-stories.mjs";

const badge = {
  id: "Badge",
  name: "Badge",
  api: [
    { name: "number text", kind: "text", default: "1", description: "The count." },
    {
      name: "tone",
      kind: "variant",
      default: "base",
      values: [{ value: "base" }, { value: "static light" }],
    },
    {
      name: "size",
      kind: "variant",
      default: "extra large",
      values: [{ value: "small" }, { value: "extra large" }],
    },
  ],
};

test("Controls use registry variant vocabularies and include optional fields", () => {
  const args = storyArgTypes({api: [
    {name:"is checked",kind:"variant",values:[{value:"false"},{value:"true"},{value:"mixed"}]},
    {name:"id",kind:"string"},
    {name:"is required",kind:"boolean"},
  ]});
  assert.deepEqual(args.isChecked, {control:"inline-radio",options:["false","true","mixed"]});
  assert.deepEqual(args.id, {control:"text"});
  assert.deepEqual(args.isRequired, {control:"boolean"});
});

test("a behaviour fixture receives the default playground args", () => {
  const rendered = renderStories(badge, { fixture: true });
  assert.match(rendered, /import Example from "\.\.\/fixtures\/BadgeExample.svelte"/);
  assert.match(rendered, /render: template/);
  assert.match(rendered, /<Example \{\.\.\.args\} \/>/);
  assert.equal(rendered.match(/<Story /g).length, 1);
});

test("defaultArgs takes every contract default, camelCased", () => {
  assert.deepEqual(defaultArgs(badge), {
    numberText: "1",
    tone: "base",
    size: "extra large",
  });
});

test("defaultArgs skips instances and slots — they have no default", () => {
  const args = defaultArgs({
    id: "Alert",
    api: [
      { name: "content", kind: "slot" },
      { name: "leading icon", kind: "instance" },
      { name: "tone", kind: "variant", default: "base", values: [{ value: "base" }] },
    ],
  });
  assert.deepEqual(args, { tone: "base" });
});

test("string identifier examples initialise the default without extra stories", () => {
  const icon = {
    id: "Icon",
    name: "Icon",
    api: [{ name: "name", kind: "string", values: [{ value: "search" }, { value: "check_circle" }] }],
  };
  assert.deepEqual(defaultArgs(icon), { name: "search" });
  const rendered = renderStories(icon);
  assert.match(rendered, /name="default" args=\{\{ name: "search" \}\}/);
  assert.doesNotMatch(rendered, /name="name:/);
  assert.equal(rendered.match(/<Story /g).length, 1);
});

test("renderStories emits only the default while keeping all variant Controls", () => {
  const rendered = renderStories(badge);
  assert.match(rendered, /GENERATED by tools\/build-ui-stories\.mjs/);
  assert.match(rendered, /import \{ Badge \} from "@stylos\/ui";/);
  assert.match(rendered, /title: "Components\/Badge"/);
  assert.match(rendered, /name="default" args=\{\{ numberText: "1", tone: "base", size: "extra large" \}\}/);
  assert.equal(rendered.match(/<Story /g).length, 1);
  assert.doesNotMatch(rendered, /name="(?:tone|size):/);
  assert.match(rendered, /"tone":\{"control":"inline-radio","options":\["base","static light"\]/);
  assert.match(rendered, /"size":\{"control":"inline-radio","options":\["small","extra large"\]/);
});

test("event callbacks do not become serializable story args or Controls", () => {
  const entry = {id:"Button Base",name:"Button Base",api:[{name:"onclick",kind:"event"}]};
  assert.deepEqual(defaultArgs(entry), {});
  assert.equal(storyArgTypes(entry).onclick.control, false);
  assert.doesNotMatch(renderStories(entry), /onclick:/);
});
