import test from "node:test";
import assert from "node:assert/strict";

import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import {
  buildUiIcons,
  readIconSvg,
  readIcons,
  renderIconsModule,
  OUT_FILE,
  SOURCE_DIR,
} from "./build-ui-icons.mjs";

/** A scratch root with the given `name → svg` pairs under the source dir. */
function scratchRoot(files) {
  const root = mkdtempSync(path.join(tmpdir(), "stylos-ui-icons-"));
  mkdirSync(path.join(root, SOURCE_DIR), { recursive: true });
  mkdirSync(path.join(root, path.dirname(OUT_FILE)), { recursive: true });
  for (const [name, svg] of Object.entries(files)) {
    writeFileSync(path.join(root, SOURCE_DIR, `${name}.svg`), svg);
  }
  return root;
}

const ONE_PATH =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" fill="currentColor" data-icon="check"><path d="M1 -2Z"/></svg>\n';

test("readIconSvg takes the viewBox and every path, with fill-rule when present", () => {
  const parsed = readIconSvg("many", '<svg viewBox="0 0 24 24"><path d="M1Z"/><path d="M2Z" fill-rule="evenodd"/></svg>');
  assert.deepEqual(parsed, {
    viewBox: "0 0 24 24",
    paths: [{ d: "M1Z" }, { d: "M2Z", fillRule: "evenodd" }],
  });
});

test("readIconSvg stops on a file it cannot read whole", () => {
  // These files are generated, so anything unreadable means the generator
  // upstream changed — a half-read drawing must not reach the component.
  assert.throws(() => readIconSvg("x", "<svg><path d=\"M1Z\"/></svg>"), /no viewBox/);
  assert.throws(() => readIconSvg("x", '<svg viewBox="0 0 1 1"></svg>'), /no <path>/);
  assert.throws(() => readIconSvg("x", '<svg viewBox="0 0 1 1"><path fill="red"/></svg>'), /<path> with no d/);
});

test("readIcons keys by Material Symbols name, in filename order", () => {
  const root = scratchRoot({ search: ONE_PATH, add: ONE_PATH, check: ONE_PATH });
  assert.deepEqual(readIcons(root).map(([name]) => name), ["add", "check", "search"]);
});

test("readIcons on a tree with no set is empty rather than an error", () => {
  const root = mkdtempSync(path.join(tmpdir(), "stylos-ui-icons-"));
  assert.deepEqual(readIcons(root), []);
});

test("renderIconsModule emits the drawings and a union of the names present", () => {
  const module = renderIconsModule([
    ["add", { viewBox: "0 -960 960 960", paths: [{ d: "M1Z" }] }],
    ["check", { viewBox: "0 -960 960 960", paths: [{ d: "M2Z", fillRule: "evenodd" }] }],
  ]);

  assert.match(module, /GENERATED by tools\/build-ui-icons\.mjs/);
  assert.ok(module.includes('"add": { viewBox: "0 -960 960 960", paths: [{ d: "M1Z" }] },'));
  assert.ok(module.includes('{ d: "M2Z", fillRule: "evenodd" }'));
  assert.ok(module.includes('export type IconName =\n  | "add"\n  | "check";'));
  // The shape a replacement set has to satisfy is the same one — SPEC 0012 §4.
  assert.ok(module.includes("export type IconDrawing"));
});

test("renderIconsModule on an empty set still type-checks", () => {
  const module = renderIconsModule([]);
  assert.ok(module.includes("export const icons: Record<string, IconDrawing> = {\n\n};"));
  assert.ok(module.includes("export type IconName =\n  never;"));
});

test("buildUiIcons writes icons.ts", () => {
  const root = scratchRoot({ search: ONE_PATH });
  assert.equal(buildUiIcons(root), OUT_FILE);

  const module = readFileSync(path.join(root, OUT_FILE), "utf8");
  assert.ok(module.includes('"search": { viewBox: "0 -960 960 960", paths: [{ d: "M1 -2Z" }] },'));
});

test("the committed set is readable, every file of it", () => {
  const root = path.resolve(import.meta.dirname, "..");
  const icons = readIcons(root);

  assert.ok(icons.length > 0, "the set is not empty");
  for (const [name, drawing] of icons) {
    assert.match(drawing.viewBox, /^-?\d+ -?\d+ \d+ \d+$/, `${name} viewBox`);
    assert.ok(drawing.paths.length > 0, `${name} has a path`);
  }
});
