import test from "node:test";
import assert from "node:assert/strict";

import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { buildUiCss, renderAggregate, OUT_DIR, AGGREGATE } from "./build-ui-css.mjs";

/** A scratch repository root: a registry, component directories, a package.json. */
function scratchRoot(components) {
  const root = mkdtempSync(path.join(tmpdir(), "stylos-ui-css-"));
  mkdirSync(path.join(root, "docs/components/registry"), { recursive: true });
  mkdirSync(path.join(root, "packages/ui"), { recursive: true });
  writeFileSync(
    path.join(root, "packages/ui/package.json"),
    JSON.stringify({ name: "@stylos/ui", version: "0.1.0" })
  );
  for (const { id, slug, css } of components) {
    writeFileSync(path.join(root, "docs/components/registry", `${slug}.yaml`), `id: "${id}"\n`);
    const dir = path.join(root, "packages/ui/src/components", slug);
    mkdirSync(dir, { recursive: true });
    if (css !== null) writeFileSync(path.join(dir, `${slug}.css`), css);
  }
  return root;
}

test("buildUiCss copies each component's CSS unchanged and writes the aggregate", () => {
  const badgeCss = ".stylos-badge {\n  color: var(--stylos-text-base);\n}\n";
  const labelCss = ".stylos-label {\n  gap: var(--stylos-dimension-space-s-0_500);\n}\n";
  const root = scratchRoot([
    { id: "Badge", slug: "badge", css: badgeCss },
    { id: "Label", slug: "label", css: labelCss },
  ]);

  const written = buildUiCss(root);
  assert.deepEqual(written, [
    `${OUT_DIR}/badge.css`,
    `${OUT_DIR}/label.css`,
    `${OUT_DIR}/${AGGREGATE}`,
  ]);

  // The copy is the authored file, byte for byte — no transform.
  assert.equal(readFileSync(path.join(root, OUT_DIR, "badge.css"), "utf8"), badgeCss);
  assert.equal(readFileSync(path.join(root, OUT_DIR, "label.css"), "utf8"), labelCss);

  const aggregate = readFileSync(path.join(root, OUT_DIR, AGGREGATE), "utf8");
  assert.match(aggregate, /GENERATED by tools\/build-ui-css\.mjs/);
  assert.match(aggregate, /@stylos\/ui 0\.1\.0 — 2 components: Badge, Label\./);
  assert.ok(aggregate.includes(badgeCss) && aggregate.includes(labelCss));
  assert.ok(aggregate.indexOf(".stylos-badge") < aggregate.indexOf(".stylos-label"), "registry order");
  // tokens.css is linked by the consumer, never bundled (SPEC 0010 §2.2).
  assert.match(aggregate, /tokens\.css is not included/);
  assert.ok(!aggregate.includes(":root"));
});

test("buildUiCss exports only built components", () => {
  const root = scratchRoot([{ id: "Badge", slug: "badge", css: ".stylos-badge {}\n" }]);
  // An entry with no component directory: in the registry, not in the export.
  writeFileSync(path.join(root, "docs/components/registry/loader.yaml"), 'id: "Loader"\n');

  buildUiCss(root);
  const out = readFileSync(path.join(root, OUT_DIR, AGGREGATE), "utf8");
  assert.match(out, /1 component: Badge\./);
  assert.ok(!out.includes("Loader"));
});

test("buildUiCss fails on a component directory with no authored CSS", () => {
  const root = scratchRoot([{ id: "Badge", slug: "badge", css: null }]);
  assert.throws(() => buildUiCss(root), /badge\.css is missing/);
});

test("renderAggregate names the version and the components in the header", () => {
  const out = renderAggregate("0.2.0", [{ id: "Badge", css: ".stylos-badge {}\n" }]);
  assert.match(out, /@stylos\/ui 0\.2\.0 — 1 component: Badge\./);
  assert.match(out, /\/\* Badge \*\/\n\.stylos-badge \{\}/);
});
