import test from "node:test";
import assert from "node:assert/strict";

import { camelName, pascalName, typeName, fieldFor, renderProps } from "./build-ui-types.mjs";

// The §3 mapping rule, checked against the shapes lib/registry.mjs produces.

test("camelName follows the §3 rule", () => {
  assert.equal(camelName("number text"), "numberText");
  assert.equal(camelName("text case"), "textCase");
  assert.equal(camelName("size"), "size");
  assert.equal(camelName("is read-only"), "isReadonly");
});

test("pascalName and typeName follow the component id", () => {
  assert.equal(pascalName("Badge"), "Badge");
  assert.equal(pascalName("Checkbox Input"), "CheckboxInput");
  assert.equal(typeName("Checkbox Input"), "CheckboxInputProps");
});

test("a variant becomes a union of its values, verbatim", () => {
  const { propName, type } = fieldFor({
    name: "tone",
    kind: "variant",
    values: [{ value: "base" }, { value: "static light" }],
  });
  assert.equal(propName, "tone");
  assert.equal(type, '"base" | "static light"');
});

test("text, boolean, instance and slot map per the table", () => {
  assert.equal(fieldFor({ name: "label text", kind: "text" }).type, "string");
  assert.equal(fieldFor({ name: "has icon", kind: "boolean" }).type, "boolean");
  assert.equal(fieldFor({ name: "leading icon", kind: "instance" }).type, "Component | Snippet");
  assert.equal(fieldFor({ name: "content", kind: "slot" }).type, "Snippet");
});

test("a sole slot is named children", () => {
  assert.equal(fieldFor({ name: "content", kind: "slot" }, { soleSlot: true }).propName, "children");
  assert.equal(fieldFor({ name: "content", kind: "slot" }, { soleSlot: false }).propName, "content");
});

test("an unknown kind fails loudly rather than generating nothing", () => {
  assert.throws(() => fieldFor({ name: "x", kind: "mystery" }), /unknown kind/);
});

test("a variant with no values fails rather than emitting never", () => {
  assert.throws(() => fieldFor({ name: "tone", kind: "variant", values: [] }), /no values/);
});

test("renderProps emits the whole generated file", () => {
  const rendered = renderProps({
    id: "Badge",
    api: [
      { name: "number text", kind: "text", description: "The count." },
      { name: "size", kind: "variant", values: [{ value: "small" }, { value: "extra large" }] },
    ],
  });
  assert.match(rendered, /GENERATED by tools\/build-ui-types\.mjs/);
  assert.match(rendered, /export type BadgeProps = \{/);
  assert.match(rendered, /numberText\?: string;/);
  assert.match(rendered, /size\?: "small" \| "extra large";/);
  assert.match(rendered, /\/\*\* The count\. \*\//);
  assert.doesNotMatch(rendered, /import type/, "no svelte import when nothing needs it");
});

test("renderProps imports svelte types only when a slot or instance needs them", () => {
  const rendered = renderProps({
    id: "Alert",
    api: [{ name: "content", kind: "slot" }],
  });
  assert.match(rendered, /import type \{ Component, Snippet \} from "svelte";/);
  assert.match(rendered, /children\?: Snippet;/);
});

test("renderProps refuses an entry with no api", () => {
  assert.throws(() => renderProps({ id: "Ghost", api: [] }), /no api/);
});
