import test from "node:test";
import assert from "node:assert/strict";

import { mkdtempSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import {
  buildIcons,
  glyphIdFor,
  listBuiltIcons,
  readManifest,
  renderIconSvg,
  roundPath,
  MANIFEST,
  OUT_DIR,
  VIEW_BOX,
} from "./build-icons.mjs";

/** A scratch root carrying one manifest. */
function scratchRoot(manifest) {
  const root = mkdtempSync(path.join(tmpdir(), "stylos-icons-"));
  mkdirSync(path.join(root, path.dirname(MANIFEST)), { recursive: true });
  writeFileSync(path.join(root, MANIFEST), manifest);
  return root;
}

const MANIFEST_TEXT = [
  "source:",
  '  family: "Material Symbols Rounded"',
  '  package: "material-symbols"',
  '  file: "material-symbols-rounded.woff2"',
  '  licence: "Apache-2.0"',
  "instance:",
  "  wght: 500",
  "  FILL: 1",
  "  GRAD: 0",
  "  opsz: 20",
  "icons:",
  '  - "chevron_right"',
  '  - "expand_more"',
  '  - "search"',
  "",
].join("\n");

/**
 * A font stand-in: names shape to a glyph id by position, and every outline is
 * a marker carrying the id and the transform it was asked for. Keeps the test
 * off the 5 MB packaged face — what is under test is the wiring, not fontkit.
 */
function fakeFont(names, { shapesInto = 1 } = {}) {
  const ids = new Map(names.map((name, i) => [name, 100 + i]));
  return {
    lookup: {
      familyName: "Material Symbols Rounded",
      layout(name) {
        const id = ids.get(name);
        return { glyphs: Array.from({ length: shapesInto }, () => ({ id })) };
      },
    },
    instanced: {
      getGlyph(id) {
        return {
          path: {
            transform(...matrix) {
              return { toSVG: () => `M${id}.125 L${matrix.join(" ")}` };
            },
          },
        };
      },
    },
  };
}

test("roundPath cuts coordinates to two decimals and leaves integers alone", () => {
  assert.equal(roundPath("M341 -669.5Q306 -454.333 312.25 -448.006"), "M341 -669.5Q306 -454.33 312.25 -448.01");
  assert.equal(roundPath("M480 -80L960 -960Z"), "M480 -80L960 -960Z");
  // The minus sign belongs to the number, not to the command before it.
  assert.equal(roundPath("L-12.349 -0.001"), "L-12.35 0");
});

test("renderIconSvg writes geometry only — no size, no ARIA", () => {
  const svg = renderIconSvg("search", "M1 -2Z");

  assert.match(svg, /GENERATED by tools\/build-icons\.mjs/);
  assert.ok(svg.includes(`viewBox="${VIEW_BOX}"`), "carries the upstream 960 em box");
  assert.ok(svg.includes('fill="currentColor"'), "inherits colour from the control");
  assert.ok(svg.includes('data-icon="search"'));
  assert.ok(svg.includes('<path d="M1 -2Z"/>'));

  // Size is the consumer's token, and the accessible name belongs on the
  // control that holds the icon — docs/foundations/icons.md.
  assert.ok(!/\swidth=/.test(svg), "no width");
  assert.ok(!/\sheight=/.test(svg), "no height");
  assert.ok(!/aria-|role=/.test(svg), "no ARIA");
});

test("readManifest reads the list in order and keeps the instance", () => {
  const root = scratchRoot(MANIFEST_TEXT);
  const manifest = readManifest(root);

  assert.deepEqual(manifest.names, ["chevron_right", "expand_more", "search"]);
  assert.deepEqual(manifest.instance, { wght: 500, FILL: 1, GRAD: 0, opsz: 20 });
  assert.equal(manifest.file, "material-symbols-rounded.woff2");
  assert.equal(manifest.package, "material-symbols");
  assert.equal(manifest.family, "Material Symbols Rounded");
});

test("readManifest rejects a name listed twice", () => {
  const root = scratchRoot(MANIFEST_TEXT.replace('  - "search"', '  - "chevron_right"'));
  assert.throws(() => readManifest(root), /"chevron_right" is listed twice/);
});

test("readManifest rejects a manifest missing a required section", () => {
  const root = scratchRoot(MANIFEST_TEXT.replace(/^instance:\n(?:  .*\n)+/m, ""));
  assert.throws(() => readManifest(root), /needs source, instance and icons/);
});

test("glyphIdFor refuses a name that is not exactly one glyph", () => {
  const names = ["chevron_right"];
  assert.equal(glyphIdFor(fakeFont(names).lookup, "chevron_right"), 100);
  assert.throws(
    () => glyphIdFor(fakeFont(names, { shapesInto: 2 }).lookup, "chevron_right"),
    /"chevron_right" is not one glyph .* it shaped into 2/s
  );
});

test("buildIcons writes one file per manifest name, in manifest order", async () => {
  const root = scratchRoot(MANIFEST_TEXT);
  const names = ["chevron_right", "expand_more", "search"];

  const written = await buildIcons(root, { open: () => fakeFont(names) });

  assert.deepEqual(written, names.map((name) => `${OUT_DIR}/${name}.svg`));
  assert.deepEqual(listBuiltIcons(root), names.map((name) => `${name}.svg`).sort());

  // y flipped on the way out, and the outline rounded by the same pass.
  const svg = readFileSync(path.join(root, OUT_DIR, "chevron_right.svg"), "utf8");
  assert.ok(svg.includes('<path d="M100.13 L1 0 0 -1 0 0"/>'), svg);
});

test("buildIcons clears the directory, so a dropped icon cannot survive", async () => {
  const root = scratchRoot(MANIFEST_TEXT);
  mkdirSync(path.join(root, OUT_DIR), { recursive: true });
  writeFileSync(path.join(root, OUT_DIR, "dropped.svg"), "<svg/>");

  await buildIcons(root, { open: () => fakeFont(["chevron_right", "expand_more", "search"]) });

  assert.ok(!readdirSync(path.join(root, OUT_DIR)).includes("dropped.svg"));
});

test("the committed set matches the committed manifest", () => {
  const root = path.resolve(import.meta.dirname, "..");
  const expected = readManifest(root).names.map((name) => `${name}.svg`).sort();

  // Fails when the manifest is edited and `npm run icons:import` is not run —
  // the set and its source may not disagree in the tree.
  assert.deepEqual(listBuiltIcons(root), expected);
});
