#!/usr/bin/env node
// Draws the Stylos icon set out of the Material Symbols variable font at one
// fixed instance, and writes each glyph as an SVG.
//
//   assets/icons/manifest.yaml  → assets/icons/svg/<name>.svg
//
//   npm run icons:import
//
// Run deliberately, never from a build: the SVGs are committed, so a change to
// the set or to the instance is a commit with a readable diff — the same rule
// assets/fonts/ follows. Nothing downstream needs the font; only regenerating
// does.
//
// Why the font is the source rather than @material-symbols/svg-NNN: the stock
// SVG packages are drawn at opsz 48 and GRAD 0 only, and the chosen instance is
// opsz 20 (docs/foundations/icons.md). Optical size is a redrawing, not a
// scale, so the difference is not recoverable downstream — it has to come off
// the variable font.
//
// Three devDependencies, against tools/README.md's dependency-free norm, and
// the exception is recorded there: instancing a variable font and reading a
// glyph outline is not something plain Node can do.

import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { parse } from "./lib/yaml.mjs";

export const MANIFEST = "assets/icons/manifest.yaml";
export const OUT_DIR = "assets/icons/svg";

// The upstream convention, kept so a Stylos icon and a stock Material Symbols
// icon are the same drawing in the same box: the font's 960-unit em, y flipped
// so the baseline-up outline reads as a top-down SVG.
export const VIEW_BOX = "0 -960 960 960";
export const UPEM = 960;

/** Path coordinates, to two decimals — 960 units against a 16–48px render. */
export function roundPath(d) {
  return d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(Number(n) * 100) / 100));
}

/**
 * One icon file. Geometry only: no width, no height, no ARIA. The size is the
 * consumer's (a token), and the accessible name belongs on the control that
 * holds the icon, never on the icon — docs/foundations/icons.md.
 */
export function renderIconSvg(name, d) {
  return (
    `<!-- GENERATED by tools/build-icons.mjs from assets/icons/manifest.yaml — do not edit. -->\n` +
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${VIEW_BOX}" fill="currentColor" data-icon="${name}">` +
    `<path d="${d}"/>` +
    `</svg>\n`
  );
}

/** Reads the manifest into the shape the import needs. */
export function readManifest(root) {
  const file = path.join(root, MANIFEST);
  const doc = parse(readFileSync(file, "utf8"), { filename: MANIFEST });

  const source = doc.get("source");
  const instance = doc.get("instance");
  const names = doc.get("icons");
  if (!source || !instance || !names) {
    throw new Error(`${MANIFEST}: needs source, instance and icons`);
  }

  const seen = new Set();
  for (const name of names) {
    if (seen.has(name)) throw new Error(`${MANIFEST}: "${name}" is listed twice`);
    seen.add(name);
  }

  return {
    file: source.get("file"),
    package: source.get("package"),
    family: source.get("family"),
    instance: Object.fromEntries(instance),
    names,
  };
}

/**
 * Opens the packaged variable font at one instance. fontkit's getVariation
 * cannot read a WOFF2 — it re-parses the compressed stream and finds no table
 * directory — so the face is decompressed to TrueType in memory first.
 * Returns { lookup, instanced }: ligatures are shaped on the base face, because
 * the variation object has no cmap, and outlines come off the instanced one.
 */
export async function openFont(root, manifest) {
  const [{ default: woff2 }, fontkit] = await Promise.all([
    import("wawoff2"),
    import("fontkit"),
  ]);

  const woff2Path = path.join(root, "node_modules", manifest.package, manifest.file);
  const ttf = Buffer.from(await woff2.decompress(readFileSync(woff2Path)));

  const lookup = fontkit.create(ttf);
  const instanced = lookup.getVariation(manifest.instance);
  return { lookup, instanced };
}

/** The single glyph a ligature name resolves to. Anything else is an error. */
export function glyphIdFor(lookup, name) {
  const run = lookup.layout(name);
  if (run.glyphs.length !== 1) {
    throw new Error(
      `"${name}" is not one glyph in ${lookup.familyName} — ` +
        `it shaped into ${run.glyphs.length}. Check the name against the Material Symbols catalogue.`
    );
  }
  return run.glyphs[0].id;
}

/**
 * Writes one SVG per manifest name into a cleared output directory, so an icon
 * dropped from the manifest cannot survive into the set. Returns the written
 * paths, relative to the root, in manifest order.
 */
export async function buildIcons(root, { open = openFont } = {}) {
  const manifest = readManifest(root);
  const { lookup, instanced } = await open(root, manifest);

  const outDir = path.join(root, OUT_DIR);
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const written = [];
  for (const name of manifest.names) {
    const glyph = instanced.getGlyph(glyphIdFor(lookup, name));
    // y up in a font, y down in SVG — flipped here rather than by a transform
    // on the element, so the file is inert geometry a sprite can also carry.
    const d = roundPath(glyph.path.transform(1, 0, 0, -1, 0, 0).toSVG());
    writeFileSync(path.join(outDir, `${name}.svg`), renderIconSvg(name, d));
    written.push(`${OUT_DIR}/${name}.svg`);
  }
  return written;
}

/** Every SVG in the output directory, whether or not the manifest names it. */
export function listBuiltIcons(root) {
  try {
    return readdirSync(path.join(root, OUT_DIR))
      .filter((file) => file.endsWith(".svg"))
      .sort();
  } catch {
    return [];
  }
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMain) {
  const root = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
  const manifest = readManifest(root);
  const written = await buildIcons(root);
  const axes = Object.entries(manifest.instance)
    .map(([axis, value]) => `${axis} ${value}`)
    .join(", ");
  console.log(`OK: ${written.length} icons from ${manifest.family} at ${axes} → ${OUT_DIR}/`);
}
