import test from "node:test";
import assert from "node:assert/strict";

import { defaultArgs, renderStories } from "./build-ui-stories.mjs";

const badge = {
  id: "Badge",
  name: "Badge",
  api: [
    { name: "number text", kind: "text", default: "1", description: "The count." },
    {
      name: "tone",
      kind: "variant",
      default: "base",
      values: [{ value: "base" }, { value: "static light" }],
    },
    {
      name: "size",
      kind: "variant",
      default: "extra large",
      values: [{ value: "small" }, { value: "extra large" }],
    },
  ],
};

test("defaultArgs takes every contract default, camelCased", () => {
  assert.deepEqual(defaultArgs(badge), {
    numberText: "1",
    tone: "base",
    size: "extra large",
  });
});

test("defaultArgs skips instances and slots — they have no default", () => {
  const args = defaultArgs({
    id: "Alert",
    api: [
      { name: "content", kind: "slot" },
      { name: "leading icon", kind: "instance" },
      { name: "tone", kind: "variant", default: "base", values: [{ value: "base" }] },
    ],
  });
  assert.deepEqual(args, { tone: "base" });
});

test("renderStories emits a default story and a case per documented variant value", () => {
  const rendered = renderStories(badge);
  assert.match(rendered, /GENERATED by tools\/build-ui-stories\.mjs/);
  assert.match(rendered, /import \{ Badge \} from "@stylos\/ui";/);
  assert.match(rendered, /title: "Components\/Badge"/);
  assert.match(rendered, /<Story name="default"/);
  assert.match(rendered, /<Story name="tone: static light"/);
  assert.match(rendered, /<Story name="size: small"/);
  // A variant case keeps every other prop at its default.
  assert.match(
    rendered,
    /name="tone: static light" args=\{\{ numberText: "1", tone: "static light", size: "extra large" \}\}/
  );
  // default story + 2 tone values + 2 size values
  assert.equal(rendered.match(/<Story /g).length, 5);
});
