import test from "node:test";
import assert from "node:assert/strict";

import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { FONT_FACES } from "./lib/theme.mjs";
import { buildUiFonts, renderFontsCss, OUT_DIR, FONTS_CSS, SOURCE_DIR } from "./build-ui-fonts.mjs";

/** A scratch root with a woff2 stub per FONT_FACES entry (minus `omit`). */
function scratchRoot({ omit } = {}) {
  const root = mkdtempSync(path.join(tmpdir(), "stylos-ui-fonts-"));
  mkdirSync(path.join(root, SOURCE_DIR), { recursive: true });
  for (const face of FONT_FACES) {
    if (face.file === omit) continue;
    writeFileSync(path.join(root, SOURCE_DIR, face.file), `stub of ${face.file}`);
  }
  return root;
}

test("buildUiFonts copies every declared subset and writes fonts.css", () => {
  const root = scratchRoot();

  const written = buildUiFonts(root);
  assert.deepEqual(written, [
    ...FONT_FACES.map((face) => `${OUT_DIR}/assets/fonts/${face.file}`),
    `${OUT_DIR}/${FONTS_CSS}`,
  ]);

  // The copy is the committed file, byte for byte — never fetched, never transformed.
  for (const face of FONT_FACES) {
    assert.equal(
      readFileSync(path.join(root, OUT_DIR, "assets/fonts", face.file), "utf8"),
      `stub of ${face.file}`
    );
  }

  const css = readFileSync(path.join(root, OUT_DIR, FONTS_CSS), "utf8");
  assert.match(css, /GENERATED by tools\/build-ui-fonts\.mjs/);
  assert.match(css, /Georama, JetBrains Mono/);
  for (const face of FONT_FACES) {
    assert.ok(css.includes(`url("assets/fonts/${face.file}")`), face.file);
    assert.ok(css.includes(`unicode-range: ${face.range};`), `${face.file} range`);
  }
  // tokens.css names the families; fonts.css never restates the variables.
  assert.ok(!css.includes("--stylos-"));
});

test("renderFontsCss declares one @font-face per face", () => {
  const css = renderFontsCss(FONT_FACES);
  assert.equal(css.match(/@font-face/g).length, FONT_FACES.length);
  assert.match(css, /font-display: swap/);
});

test("buildUiFonts fails on a subset FONT_FACES names but assets/fonts lacks", () => {
  const root = scratchRoot({ omit: "georama-latin.woff2" });
  assert.throws(() => buildUiFonts(root), /georama-latin\.woff2 is missing/);
});
