#!/usr/bin/env node
// Renders the canonical token set as Markdown, for documentation.
//
//   npm run tokens:report                # everything
//   npm run tokens:report radius space   # named collections only
//
// This script is why no foundation document transcribes a token value. A
// value copied into Markdown is wrong at the next tweak in Figma, and a stale
// value in a foundation document is worse than no value — it gets built
// against. Anything this cannot render is a gap in it, not a reason to copy
// values into prose.
//
// Reads tokens/*.yaml, never the raw export. Only the Markdown goes to stdout,
// so `npm run tokens:report > file.md` is clean.

import path from "node:path";
import { fileURLToPath } from "node:url";

import { loadCanonical, groupByPrefix, resolve, themeModes } from "./lib/tokens.mjs";

/**
 * A token with a reference stores no value, so the value shown is resolved by
 * following the reference. That is the whole point of not storing it twice.
 */
function renderValue(all, collection, tokenPath, mode) {
  let resolved;
  try {
    resolved = resolve(all, collection.name, tokenPath, mode);
  } catch {
    return "—";
  }
  const { value, alpha } = resolved;
  if (typeof value !== "string" || !value.startsWith("#")) return `\`${value}\``;
  return alpha === 1 ? `\`${value}\`` : `\`${value}\` @ ${Math.round(alpha * 100)}%`;
}

function renderRef(token) {
  if (!token.ref) return "—";
  if (token.ref.has("default")) return `\`${token.ref.get("default")}\``;
  return [...token.ref].map(([mode, target]) => `${mode}: \`${target}\``).join("<br>");
}

function renderCollection(all, collection, lines) {
  const { name, layer, modes, tokens } = collection;
  const hasRefs = [...tokens.values()].some((t) => t.ref);

  lines.push(`## ${name}`, "");
  lines.push(`${tokens.size} tokens · ${layer} · ${modes.length === 1 ? "single mode" : `modes: ${modes.join(", ")}`}`, "");

  // A collection without theme modes of its own can still reference one that
  // has them, so the columns are the themes its values actually resolve in.
  const columns = modes.length > 1 ? modes : themeModes(all);
  const header = ["Token", ...columns, ...(hasRefs ? ["Reference"] : [])];
  const alignment = header.map(() => "---");

  for (const [prefix, group] of groupByPrefix(tokens)) {
    if (prefix !== null) lines.push(`### ${name} / ${prefix}`, "");
    lines.push(`| ${header.join(" | ")} |`);
    lines.push(`| ${alignment.join(" | ")} |`);

    for (const [tokenPath, token] of group) {
      const cells = [
        `\`${tokenPath}\``,
        ...columns.map((mode) => renderValue(all, collection, tokenPath, mode)),
        ...(hasRefs ? [renderRef(token)] : []),
      ];
      lines.push(`| ${cells.join(" | ")} |`);
    }
    lines.push("");
  }
}

export function renderReport(collections, all = collections) {
  const lines = [];
  const { imported, figmaFile } = collections[0].source;

  lines.push("# Token values", "");
  lines.push(
    `Generated by \`npm run tokens:report\` from \`tokens/\`, normalized from the ` +
      `**${figmaFile}** export of ${imported || "an unrecorded date"}. ` +
      `Do not copy these values into another document — ` +
      `re-run the command instead.`,
    ""
  );

  lines.push("| Collection | Layer | Modes | Tokens |");
  lines.push("| --- | --- | --- | ---: |");
  for (const c of collections) {
    lines.push(`| \`${c.name}\` | ${c.layer} | ${c.modes.join(", ")} | ${c.tokens.size} |`);
  }
  lines.push("");

  for (const collection of collections) renderCollection(all, collection, lines);

  return lines.join("\n").replace(/\n+$/, "") + "\n";
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);

if (isMain) {
  const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
  const names = process.argv.slice(2).filter((a) => !a.startsWith("--"));

  // Every collection is loaded whatever is asked for, because a reference
  // reaches across them: rendering `color` alone still has to follow into
  // `palette` to show a value.
  let all;
  let collections;
  try {
    all = loadCanonical(root);
    collections = names.length ? loadCanonical(root, names) : all;
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }

  // The only write to stdout in this file — everything else is stderr, so the
  // report can be redirected to a file without picking up progress noise.
  console.log(renderReport(collections, all));
}
